### PR TITLE
47 create first test for react native

### LINKED ISSUE #47: Create first test for react-native
## Describe the feature
Create a test for React Native with documentation to know how to create a test and how to run them

## TO DO
- Create a test folder for React Native
- Create a first test file
- Create a how-to-use file to document test

## Extra links (Optional)
Try to use this framework : [detox](https://github.com/wix/detox)

## Screenshots (Optional)
_Add any screenshot_

### PR DESCRIPTION
**Pull request by osvegn**
# New feature
- Add detox framework as dependency
- Create some tests to be as example of how to test using detox
- Create a README  to explain how to run tests
# Updated feature

# Bug fixed

### CODE REVIEW

**Review by 31Nathan — DISMISSED** [review]
LGTM

**Review by osvegn — COMMENTED** [review]
Look good

**Review by osvegn — COMMENTED** [review]
Test

**Review by 31Nathan — APPROVED** [review]
LGTM

**Review by JohanCDev — APPROVED** [review]
ntr

**Pull request merged**
