### PR TITLE
implement add area page and SettingsPage

### LINKED ISSUE #38: Implement Add Area page
## Related feature
Implement the figma

## Screenshots (Optional)
Capture d’écran 2023-01-24 à 10 52 03

### PR DESCRIPTION
**Pull request by JohanCDev**
# New feature
Two new screens

Closes #38 #37 
Capture d’écran 2023-01-29 à 21 37 33
Capture d’écran 2023-01-29 à 21 37 29
Capture d’écran 2023-01-29 à 21 36 46
Capture d’écran 2023-01-29 à 21 36 37

### CODE REVIEW

**Review by STom6 — DISMISSED** [review]
LGTM

**Review by osvegn — CHANGES_REQUESTED** [review]
Can you add some screenshots on PR description ? Otherwise it looks good

**Review by 31Nathan — DISMISSED** [review]
LGTM

**Review by osvegn — DISMISSED** [review]
Look good

**Review by STom6 — DISMISSED** [review]
lgtm

**Review by 31Nathan — APPROVED** [review]
LGTM

**Review by osvegn — APPROVED** [review]
Look good

**Pull request merged**
