### PR TITLE
14 about server management

### LINKED ISSUE #14: About server management

### PR DESCRIPTION
**Pull request by CedricCORGE**
# New feature
Server response to the following route: http://localhost:8080/about.json
This route provide a detailled descriptions of actions/reactions offer by our application

Closes #14

### CODE REVIEW

**Comment by JohanCDev** [comment]
Do we really want to keep Hello World as the welcome message

**Review by JohanCDev — DISMISSED** [review]

**Review by 31Nathan — DISMISSED** [review]
LGTM

**Review by STom6 — DISMISSED** [review]
LGTM

**Review by osvegn — APPROVED** [review]
Look good

**Review by STom6 — APPROVED** [review]
LGTM

**Pull request merged**
