### PR TITLE
218 improvement adding missing documentation to the server

### LINKED ISSUE #218: [IMPROVEMENT]: Adding missing documentation to the server
### Description

adding missing documentation to the server

### To do

adding missing documentation to the server

### Priority

Medium

### Project parts

- [X] Server
- [ ] Application
- [ ] Web
- [ ] Automation

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by STom6**
# New feature
Add documentation to the back.
# Updated feature
Remove unused file / line
# Bug fixed

### CODE REVIEW

**Review by CedricCORGE — DISMISSED** [review]
lgtm

**Review by JohanCDev — DISMISSED** [review]
Ntr

**Review by 31Nathan — APPROVED** [review]
LGTM

**Review by JohanCDev — APPROVED** [review]
Ntr

**Review by CedricCORGE — APPROVED** [review]
lgtm

**Pull request merged**
