### PR TITLE
Implement sign in with facebook option

### LINKED ISSUE #41: Implement OAuth authentification
## Describe the feature
 Implement the authentification using differents services like facebook, google or apple

## TO DO
Add redirection to auth page front-side and communicate with back-end the user information

## Extra links (Optional)
_Add any other extra links_

## Screenshots (Optional)
_Add any screenshot_

### PR DESCRIPTION
**Pull request by CedricCORGE**
# New feature

Implement the facebook login in the application, email/password  and facebook login in the web app. 

# Updated feature

# Bug fixed

### CODE REVIEW

**Review by 31Nathan — DISMISSED** [review]
LGTM

**Review by 31Nathan — CHANGES_REQUESTED** [review]
Binary files on this PR, Please remove them

**Review by 31Nathan — DISMISSED** [review]
LGTM

**Review by STom6 — APPROVED** [review]
lgtm

**Review by 31Nathan — APPROVED** [review]

**Pull request merged**
