### PR TITLE
94 create server documentation

### LINKED ISSUE #94: Create server documentation
## Describe the feature
Create server documentation, which is js code

## TO DO
Use a program to generate documentation and configure it to a folder ${REPO_ROOT}/Server/docs

## Extra links (Optional)
_Add any other extra links_

## Screenshots (Optional)
_Add any screenshot_

### PR DESCRIPTION
**Pull request by osvegn**
# New feature
- Create a workflow to deploy the documentation. It can be run manually, or it is run on push in main branch. The generated documentation is available in GitHub page
# Updated feature
- Improve server documentation. Some new documentation balise are used.
# Bug fixed

### CODE REVIEW

**Review by 31Nathan — DISMISSED** [review]
LGTM

**Review by JohanCDev — DISMISSED** [review]
NTR

**Review by 31Nathan — APPROVED** [review]
LGTM

**Review by CedricCORGE — APPROVED** [review]
LGTM

**Pull request merged**
