### PR TITLE
7 create an apk release of the android app

### LINKED ISSUE #7: Create an APK release of the android app
Use this documentation to know how to do it : [here](https://medium.com/geekculture/react-native-generate-apk-debug-and-release-apk-4e9981a2ea51)
Update the CI to create release using workflow dispatch (with options such as name or version)
Publish the artifact on Github

### PR DESCRIPTION
**Pull request by osvegn**
# New feature
- Route to {WEB_URL}/client.apk which download client.apk build by the client_mobile
- Remove useless binary files
# Updated feature
- Improved Dockerfile clarity and efficiency

# Bug fixed

### CODE REVIEW

**Comment by JohanCDev** [comment]
There is a lot of file '.bin', are they really useful ?

**Review by 31Nathan — DISMISSED** [review]

**Comment by osvegn** [comment]
> There is a lot of file '.bin', are they really useful ?

These binary files are delete, not add.

**Review by JohanCDev — DISMISSED** [review]
Lgtm

**Review by STom6 — DISMISSED** [review]
lgtm

**Review by CedricCORGE — APPROVED** [review]
ntr

**Review by JohanCDev — APPROVED** [review]
lgtm

Sad that it was only this

**Review by STom6 — APPROVED** [review]
lgtm

**Review by 31Nathan — APPROVED** [review]
LGTM

**Pull request merged**
