### PR TITLE
Create the connexion and the inscription page

### LINKED ISSUE #15: Create the connexion absolute front-end
Create the connexion screen front-end, it doesn't need to have any back-end connected to.

You can see how it should look like with the image linked
Capture d’écran 2023-01-17 à 14 21 23

### PR DESCRIPTION
**Pull request by JohanCDev**
# New feature
Implement two screens, being the connexion and the inscription page. It's strictly front-end, no back-end is implemented. The app looks like this on iOS, Android
Capture d’écran 2023-01-18 à 16 03 40
Capture d’écran 2023-01-18 à 16 03 47

Closes #15 #16

### CODE REVIEW

**Review by STom6 — DISMISSED** [review]
LGTM

**Review by osvegn — DISMISSED** [review]
Look good

**Review by CedricCORGE — DISMISSED** [review]

**Review by 31Nathan — APPROVED** [review]
LGTM

**Review by 31Nathan — APPROVED** [review]

**Review by osvegn — APPROVED** [review]
Look good

**Pull request merged**
