### PR TITLE
Add server status and modification on app

### LINKED ISSUE #112: Server status on app
## Describe the feature
Show on app if it is connected to the server.

## TO DO
Ask the server on app launch.
If no answer, write a message on app screen ("Can't connect to server({IP})")

## Extra links (Optional)
_Add any other extra links_

## Screenshots (Optional)
_Add any screenshot_

### PR DESCRIPTION
**Pull request by JohanCDev**
# New feature
Allow the user to change his server address, and fix the repetitive initializations of firebase app
Capture d’écran 2023-02-09 à 22 46 44
Capture d’écran 2023-02-09 à 22 46 51
Capture d’écran 2023-02-09 à 22 46 59
Capture d’écran 2023-02-09 à 22 47 07

# Updated feature

# Bug fixed

### CODE REVIEW

**Review by STom6 — APPROVED** [review]
lgtm

**Comment by JohanCDev** [comment]
I'll improve Settings page by adding a logo on left of textInput so we can have a coherence between components.

**Review by osvegn — APPROVED** [review]
Look good

**Comment by osvegn** [comment]
Close #110

**Review by 31Nathan — APPROVED** [review]
LGTM

**Pull request merged**
